### ISSUE TITLE
Share motor source plox 

### ISSUE THREAD

**Issue by SamarV-121** [realme-kernel-opensource/realmeX-kernel-source#1]
https://github.com/realme-kernel-opensource/realmeX-kernel-source/blob/d6ba7a7afd4f6d8d081feeb4d650264d0ca6b8f9/drivers/misc/oppo_motor
;_;

**Comment by nibaji** [comment]
drv8834?

**Comment by wqrqwerqrw** [comment]
https://github.com/oppo-source/FindX-8.1-kernel-source/tree/57b5a2f02917903bf5b9093b0de89b839aabd1a5/drivers/misc/oppo

this might be useful?

**Comment by wqrqwerqrw** [comment]
https://github.com/oppo-source/Reno-5G-9.0-kernel-source/tree/91ea7afcc60019b6278e69f5fd5fe0d0dc8f80fb/drivers/misc/oppo_motor

**Comment by thebestuwu** [comment]
https://github.com/realme-kernel-opensource/realmeX-kernel-source/blob/master/drivers/misc/motor.c

**Comment by wqrqwerqrw** [comment]
#include "oppo_motor/oppo_motor.h"
#include "oppo_motor/oppo_motor_notifier.h"

no oppo_motor.h and oppo_motor_notifoer.h

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    




    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    add motor code masterrealme-kernel-opensource committed 10 minutes ago1 parent d6ba7a7 commit e3b984559c5c62e679c41753057ee782454086db                



    On 9/6/2019 11:05，Wqr_<notifications@github.com> wrote： 


#include "oppo_motor/oppo_motor.h"
#include "oppo_motor/oppo_motor_notifier.h"
no oppo_motor.h and oppo_motor_notifoer.h

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    


add motor code masterrealme-kernel-opensource committed 10 minutes ago1 parent d6ba7a7 commit e3b984559c5c62e679c41753057ee782454086db                



    On 9/6/2019 07:37，thebestuwu<notifications@github.com> wrote： 


https://github.com/realme-kernel-opensource/realmeX-kernel-source/blob/master/drivers/misc/motor.c

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
