### ISSUE TITLE
Please upgrade the kernel source to the latest version and open techpack/audio!

### ISSUE THREAD

**Issue by Art-Chen** [realme-kernel-opensource/realmeX-kernel-source#3]
@realme-kernel-opensource The sources you are opened is too old that I can build it but didn't boot up, only boot up when I  pull the dtb from the stock rom. But the QMI stop working, and Much more devices didn't work properly.
Also, Tell me the version of this source please!
By the way, Please open the **techpack/audio** sources because of GPL v2 License.

**Comment by chankruze** [comment]
It's almost 13 different builds i tried ...  not booting any. Complete the source.

**Comment by chankruze** [comment]
@Art-Chen did you compiled with latest commit ?
My kernel is now 0.7 MB bigger (11.7 + 0.7) which with dtbs becomes 67.8 MB (67.1 + 0.7) and prevents flashing.

Any suggestions ?

**Comment by chankruze** [comment]
@Art-Chen please upload the dtbs you pulled from device some where and share it's url. Then i can verify i am extracting dtbs properly or not.

It booted only one with stock dtbs, since that it's bootlooping to bootloader. If i don't append 6th dtb it's just bootlooping to splash screen.

**Comment by Art-Chen** [comment]
> @Art-Chen did you compiled with latest commit ?
> I did and compressed kernel is now 0.7 MB bigger (11.7 + 0.7) which with dtbs becomes 67.8 MB (67.1 + 0.7) and prevents flashing.
> 
> Any suggestions ?
> 
> **Edit:**
> Uncompressed size is 3 MB larger then stock's

The DTBs are not so big, Maybe your dtbs issue.
Pull the DTBs from zImage of stock.
The DTBs is at the end of zImage ( Use HexEdit Tools to pull it )

**Comment by chankruze** [comment]
Now with latest source, i'am able to get 6 dtbs appended but it still booting to to bootloader. Below have all the possible tests i already tried.

S.N. | Tests | Results
------|--------|----------
1 | Stock `Image.gz` + Stock `dtbs` | Normal Booting
2 | Stock `Image.gz` + Compiled `dtbs` | Booting to `bootloader`
3 | Compiled `Image.gz` + Compiled `dtbs` | Booting to `bootloader`
4 | Compiled `Image.gz` + Stock `dtbs` | Boot looping (**splash screen** -> **blank screen**) infinite cycle
5 | Compiled `Image.gz-dtb` | Booting to `bootloader`

**Comment by Art-Chen** [comment]
> Now with latest source, i'am able to get 6 dtbs appended but it still booting to to bootloader. Before i was getting only one dtb appended.
> 
> Below are all the possible tests i already tried.
> 
> S.N.	Tests	Results	Remarks
> 1	Stock `Image.gz` + Stock `dtbs`	Normal Booting	
> 2	Stock `Image.gz` + Compiled `dtbs`	Booting to `bootloader`	As previous
> 3	Compiled `Image.gz` + Compiled `dtbs`	Booting to `bootloader`	As previous
> 4	Compiled `Image.gz` + Stock `dtbs`	Boot looping (**splash screen** -> **blank screen**) infinite cycle	As previous
> 5	Compiled `Image.gz-dtb`	Booting to `bootloader`	As previous
> **Stock DTBs**
> ![Stock-DTBs](https://user-images.githubusercontent.com/29806845/65922053-aa040080-e401-11e9-9e31-cdeaf77a9ee3.png)
> 
> **Latest Compiled DTBs**
> ![Latest-Compiled-DTBs](https://user-images.githubusercontent.com/29806845/65922071-b7b98600-e401-11e9-8ffb-e1cfd6c6e44c.png)

Aha the oss opened the other project dts, but it will not change anything. Actually They forget to pick the short_c to the dts. It’s the reason that reboot to boot loader.
Also the OSS didn’t open the devices/doc/oppo/oppo_mem* , and the shared mem commit that used for nv backup. So when using the oppo rmt_storage panic.
You can wait me to make my kernel source public. 
Now I will close this issue.

**Comment by chankruze** [comment]
@Art-Chen You pro, thanks for the explanation.
